### ISSUE TITLE
http://daveyoster.com/ not resolving

### ISSUE THREAD

**Issue by n8os** [dOst307/dOst307.github.io#1]
Domain name isn't resolving. DNS might be incorrect as it should have propagated by now. @dOst307 can you double check that daveyoster.com's DNS is set?

**Comment by n8os** [comment]
![image](https://user-images.githubusercontent.com/13957140/116305338-a49fa100-a771-11eb-8cd7-5af4eea8b608.png)

**Comment by dOst307** [comment]
Resolved
